name: Build roads data and upload as artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build

      - name: Upload roads artifact
        uses: actions/upload-artifact@v4
        with:
          name: road-network-data
          path: output/**/*
